// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Server
	ListRequest
	ListResponse
	AttachRequest
	ServerOutput
	StopResponse
	StopRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Server struct {
	Name     string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	HostName string   `protobuf:"bytes,2,opt,name=host_name,json=hostName" json:"host_name,omitempty"`
	Address  string   `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Port     string   `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	Iwad     string   `protobuf:"bytes,5,opt,name=iwad" json:"iwad,omitempty"`
	Pwads    []string `protobuf:"bytes,6,rep,name=pwads" json:"pwads,omitempty"`
	GameType string   `protobuf:"bytes,7,opt,name=game_type,json=gameType" json:"game_type,omitempty"`
	Status   string   `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
}

func (m *Server) Reset()                    { *m = Server{} }
func (m *Server) String() string            { return proto1.CompactTextString(m) }
func (*Server) ProtoMessage()               {}
func (*Server) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListResponse struct {
	Servers []*Server `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListResponse) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

type AttachRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *AttachRequest) Reset()                    { *m = AttachRequest{} }
func (m *AttachRequest) String() string            { return proto1.CompactTextString(m) }
func (*AttachRequest) ProtoMessage()               {}
func (*AttachRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ServerOutput struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *ServerOutput) Reset()                    { *m = ServerOutput{} }
func (m *ServerOutput) String() string            { return proto1.CompactTextString(m) }
func (*ServerOutput) ProtoMessage()               {}
func (*ServerOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type StopResponse struct {
}

func (m *StopResponse) Reset()                    { *m = StopResponse{} }
func (m *StopResponse) String() string            { return proto1.CompactTextString(m) }
func (*StopResponse) ProtoMessage()               {}
func (*StopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type StopRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto1.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto1.RegisterType((*Server)(nil), "proto.Server")
	proto1.RegisterType((*ListRequest)(nil), "proto.ListRequest")
	proto1.RegisterType((*ListResponse)(nil), "proto.ListResponse")
	proto1.RegisterType((*AttachRequest)(nil), "proto.AttachRequest")
	proto1.RegisterType((*ServerOutput)(nil), "proto.ServerOutput")
	proto1.RegisterType((*StopResponse)(nil), "proto.StopResponse")
	proto1.RegisterType((*StopRequest)(nil), "proto.StopRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Daemon service

type DaemonClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Attach(ctx context.Context, opts ...grpc.CallOption) (Daemon_AttachClient, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type daemonClient struct {
	cc *grpc.ClientConn
}

func NewDaemonClient(cc *grpc.ClientConn) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/proto.Daemon/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Attach(ctx context.Context, opts ...grpc.CallOption) (Daemon_AttachClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Daemon_serviceDesc.Streams[0], c.cc, "/proto.Daemon/Attach", opts...)
	if err != nil {
		return nil, err
	}
	x := &daemonAttachClient{stream}
	return x, nil
}

type Daemon_AttachClient interface {
	Send(*AttachRequest) error
	Recv() (*ServerOutput, error)
	grpc.ClientStream
}

type daemonAttachClient struct {
	grpc.ClientStream
}

func (x *daemonAttachClient) Send(m *AttachRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *daemonAttachClient) Recv() (*ServerOutput, error) {
	m := new(ServerOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *daemonClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	out := new(StopResponse)
	err := grpc.Invoke(ctx, "/proto.Daemon/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Daemon service

type DaemonServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Attach(Daemon_AttachServer) error
	Stop(context.Context, *StopRequest) (*StopResponse, error)
}

func RegisterDaemonServer(s *grpc.Server, srv DaemonServer) {
	s.RegisterService(&_Daemon_serviceDesc, srv)
}

func _Daemon_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Daemon/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonServer).Attach(&daemonAttachServer{stream})
}

type Daemon_AttachServer interface {
	Send(*ServerOutput) error
	Recv() (*AttachRequest, error)
	grpc.ServerStream
}

type daemonAttachServer struct {
	grpc.ServerStream
}

func (x *daemonAttachServer) Send(m *ServerOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *daemonAttachServer) Recv() (*AttachRequest, error) {
	m := new(AttachRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Daemon_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Daemon/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Daemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Daemon_List_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Daemon_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _Daemon_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0xad, 0x49, 0x9b, 0xb6, 0xd7, 0x14, 0x21, 0x53, 0x21, 0x0b, 0x96, 0xe0, 0x85, 0x4c, 0x15,
	0x14, 0x21, 0xc4, 0x88, 0xc4, 0x88, 0x40, 0x4a, 0xd9, 0x2b, 0x43, 0xac, 0xb6, 0x43, 0x62, 0x13,
	0x5f, 0xa8, 0xfa, 0x49, 0xfc, 0x08, 0xdf, 0x85, 0x6c, 0x27, 0x6d, 0x2a, 0xc1, 0xe4, 0xbb, 0xf7,
	0xce, 0xf7, 0xde, 0x3b, 0x88, 0x8c, 0x2c, 0xbf, 0x64, 0x39, 0xd5, 0xa5, 0x42, 0x45, 0x7b, 0xee,
	0xe1, 0x3f, 0x04, 0xc2, 0xb9, 0xc3, 0x29, 0x85, 0x6e, 0x21, 0x72, 0xc9, 0x48, 0x4c, 0x92, 0x61,
	0xea, 0x6a, 0x7a, 0x01, 0xc3, 0x95, 0x32, 0xb8, 0x70, 0xc4, 0x91, 0x23, 0x06, 0x16, 0x78, 0xb1,
	0x24, 0x83, 0xbe, 0xc8, 0xb2, 0x52, 0x1a, 0xc3, 0x02, 0x47, 0x35, 0xad, 0x5d, 0xa5, 0x55, 0x89,
	0xac, 0xeb, 0x57, 0xd9, 0xda, 0x62, 0xeb, 0x8d, 0xc8, 0x58, 0xcf, 0x63, 0xb6, 0xa6, 0x13, 0xe8,
	0xe9, 0x8d, 0xc8, 0x0c, 0x0b, 0xe3, 0x20, 0x19, 0xa6, 0xbe, 0xb1, 0xa2, 0x4b, 0x91, 0xcb, 0x05,
	0x6e, 0xb5, 0x64, 0x7d, 0x2f, 0x6a, 0x81, 0xb7, 0xad, 0x96, 0xf4, 0x0c, 0x42, 0x83, 0x02, 0x2b,
	0xc3, 0x06, 0x8e, 0xa9, 0x3b, 0x3e, 0x86, 0xd1, 0xf3, 0xda, 0x60, 0x2a, 0x3f, 0x2b, 0x69, 0x90,
	0xdf, 0x43, 0xe4, 0x5b, 0xa3, 0x55, 0x61, 0x24, 0xbd, 0x82, 0xbe, 0x8f, 0x6f, 0x18, 0x89, 0x83,
	0x64, 0x34, 0x1b, 0xfb, 0x3b, 0x4c, 0x7d, 0xf8, 0xb4, 0x61, 0xf9, 0x1d, 0x8c, 0x1f, 0x11, 0xc5,
	0xc7, 0xaa, 0xde, 0xf4, 0xe7, 0x59, 0x4e, 0x20, 0xc8, 0xcd, 0xb2, 0x3e, 0x88, 0x2d, 0x79, 0x0c,
	0x91, 0xdf, 0xf4, 0x5a, 0xa1, 0xae, 0xb0, 0x99, 0x20, 0xfb, 0x89, 0x63, 0x88, 0xe6, 0xa8, 0x74,
	0xe3, 0x88, 0x5f, 0xc2, 0xc8, 0xf7, 0xff, 0xca, 0xcc, 0xbe, 0x09, 0x84, 0x4f, 0x42, 0xe6, 0xaa,
	0xa0, 0x37, 0xd0, 0xb5, 0x79, 0x28, 0xad, 0x6d, 0xb7, 0xb2, 0x9e, 0x9f, 0x1e, 0x60, 0xf5, 0xfa,
	0x0e, 0x7d, 0x80, 0xd0, 0x27, 0xa1, 0x93, 0x7a, 0xe0, 0x20, 0xd8, 0xee, 0x5b, 0xdb, 0x37, 0xef,
	0x24, 0xe4, 0x9a, 0x58, 0x35, 0xeb, 0x6d, 0xa7, 0xd6, 0x32, 0xba, 0xff, 0xd6, 0x0e, 0xd3, 0x79,
	0x0f, 0x1d, 0x7a, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xfc, 0xf2, 0x50, 0x66, 0x02, 0x00,
	0x00,
}
