name = "tlsxctf"
hostname = "TLSXCTF"
mode = "ctf"
port = 10667
wads = ["tlsxctf1_zand.wad", "zctfconvstv2.wad"]
dmflags = 0
dmflags2 = 0
zadmflags = 0
compatflags = 0
compatflags2 = 0
zacompatflags = 0
disabled = true
