name = "zdctf"
hostname = "ZDCTF"
mode = "ctf"
port = 10666
wads = ["zdctfmp.wad", "zdctfmp2.wad", "zdctfmp3-.wad"]
dmflags = 0
dmflags2 = 0
zadmflags = 0
compatflags = 0
compatflags2 = 0
zacompatflags = 0
