name = "zdctf"
hostname = "ZDCTF"
mode = "ctf"
port = 10666
wads = ["stctfmp.wad", "stctfmp2.wad", "stctfmp3-.wad", "zctfconvstv2.wad"]
dmflags = 0
dmflags2 = 0
zadmflags = 0
compatflags = 0
compatflags2 = 0
zacompatflags = 0
